<a href="https://colab.research.google.com/github/Andreasaldivar/GOOGLE-COLLAB-QUERY/blob/main/S7_PYTHON_RECAP_FUNCTIONS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
#IMPORTS PRINCIPALES
import pandas  as pd               #LECTURA, MANEJO Y TRANSFORMACIÓN DE DATAFRAMES.
import numpy   as np               #FUNCIONES MATEMÁTICAS RELEVANTES.
import scipy   as sp               #MODELOS ESTADÍSTICOS Y MATEMÁTICOS.
import matplotlib.pyplot as plt    #GRÁFICOS.
import seaborn as sns              #GRÁFICOS PRETTY.

import warnings                                                #MANEJO DE WARNINGS - ADVERTENCIAS
warnings.simplefilter(action='ignore', category=FutureWarning) #QUITAR WARNINGS MOLESTOS
pd.set_option('display.max_columns', None)                     #ELIMINA LIMITES DE PANDAS PARA MOSTRAR COLUMNAS
pd.set_option('display.max_rows', None)                        #ELIMINA LIMITES DE PANDAS PARA MOSTRAR FILAS
pd.set_option('display.max_colwidth', None)                    #AUTOAJUSTA ANCHO DE COLUMNAS
#pd.set_option('display.float_format', lambda x: '%.2f' % x)   #PERMITE EVADIR EL MOSTRAR NÚMEROS CON NOTACIÓN CINETÍFICA

In [2]:
#CARGANDO DATA
ruta_tabla = "https://media.githubusercontent.com/media/hector1994/e_commerce_funnel_data_generator/refs/heads/master/sales_data_dirty_sp7_data.csv"
df_raw     = pd.read_csv(ruta_tabla) #DATA SIN PROCESAR.
df_raw.head()                        #MUESTRAS LOS PRIMEROS 5 REGISTROS DEL DATAFRAME - df.tail()

,order_id,order_date,customer_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount,payment_method,shipping_status
0,98c01d39-0be7-4ee0-9ecf-50a50b63159a,2024-06-12,250414,Jorge Pérez,jorge.pérez_250414@example.com,Chile,CHL,Rancagua,5054 Calle Los Pinos,P012,Headphones NoiseCancelling,Electronics,1,250.00,0.30,5.45,250.00,0.00,47.50,302.95,PayPal,Delivered
1,715759ca-06c2-4b36-b86f-177b6b154a7a,2025-05-29,269884,Isabel Castro,isabel.castro_269884@example.com,Colombia,COL,Medellín,5375 Calle Los Alamos,P015,Hair Dryer,Home,1,35.00,0.60,5.90,35.00,3.50,5.99,43.38,Credit Card,Shipped
2,46e91d25-94ff-4eca-9fe7-7d7cb4683429,2025-10-04,54582,Francisco Rojas,francisco.rojas_54582@example.com,Argentina,ARG,Mar del Plata,3777 Calle Los Pinos,P008,Office Chair,Furniture,1,200.00,15.00,27.50,200.00,10.00,36.10,253.60,PayPal,Shipped
3,df2478f3-f34f-4f18-82eb-86727241b153,2024-11-19,194401,Carlos Ramírez,carlos.ramírez_194401@example.com,Perú,PER,Piura,2115 Calle Secundaria,P015,Hair Dryer,Home,1,NaN,0.60,5.90,35.00,0.00,6.65,47.55,PayPal,Delivered
4,e6a850d8-d658-46fb-9c94-4f99af54a596,2026-01-07,104597,Pedro García,pedro.garcía_104597@example.com,Argentina,ARG,Córdoba,6181 Calle Secundaria,P002,Smartphone X,Electronics,1,800.00,0.20,5.30,800.00,40.00,144.40,909.70,Bank Transfer,Delivered

In [3]:
df_raw.head(10)

,order_id,order_date,customer_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount,payment_method,shipping_status
0,98c01d39-0be7-4ee0-9ecf-50a50b63159a,2024-06-12,250414,Jorge Pérez,jorge.pérez_250414@example.com,Chile,CHL,Rancagua,5054 Calle Los Pinos,P012,Headphones NoiseCancelling,Electronics,1,250.00,0.30,5.45,250.00,0.00,47.50,302.95,PayPal,Delivered
1,715759ca-06c2-4b36-b86f-177b6b154a7a,2025-05-29,269884,Isabel Castro,isabel.castro_269884@example.com,Colombia,COL,Medellín,5375 Calle Los Alamos,P015,Hair Dryer,Home,1,35.00,0.60,5.90,35.00,3.50,5.99,43.38,Credit Card,Shipped
2,46e91d25-94ff-4eca-9fe7-7d7cb4683429,2025-10-04,54582,Francisco Rojas,francisco.rojas_54582@example.com,Argentina,ARG,Mar del Plata,3777 Calle Los Pinos,P008,Office Chair,Furniture,1,200.00,15.00,27.50,200.00,10.00,36.10,253.60,PayPal,Shipped
3,df2478f3-f34f-4f18-82eb-86727241b153,2024-11-19,194401,Carlos Ramírez,carlos.ramírez_194401@example.com,Perú,PER,Piura,2115 Calle Secundaria,P015,Hair Dryer,Home,1,NaN,0.60,5.90,35.00,0.00,6.65,47.55,PayPal,Delivered
4,e6a850d8-d658-46fb-9c94-4f99af54a596,2026-01-07,104597,Pedro García,pedro.garcía_104597@example.com,Argentina,ARG,Córdoba,6181 Calle Secundaria,P002,Smartphone X,Electronics,1,800.00,0.20,5.30,800.00,40.00,144.40,909.70,Bank Transfer,Delivered
5,919d93a8-c8cb-4071-826f-0938fef79e96,2024-12-23,11711,Mariana Pérez,mariana.pérez_11711@example.com,Brasil,BRA,Salvador,7717 Calle Norte,P012,Headphones NoiseCancelling,Electronics,1,250.00,0.30,5.45,250.00,12.50,45.12,288.07,PayPal,Processing
6,773963bd-881b-4a32-986b-c0b8c44b897c,2025-04-11,188463,Mariana González,mariana.gonzález_188463@example.com,Brasil,BRA,Belo Horizonte,1459 Calle Secundaria,P013,Gaming Console,Electronics,4,500.00,14.00,26.00,2000.00,200.00,342.00,2168.00,Credit Card,Shipped
7,39ebde4d-15fb-46e8-a2ff-7c9c9842f7fc,2024-10-07,382498,Miguel Ruiz,miguel.ruiz_382498@example.com,México,MEX,Tijuana,3632 Calle Principal,P007,Blender,Home,1,45.00,2.20,8.30,45.00,4.50,7.70,56.50,Debit Card,NaN
8,6f337aa1-49be-479f-9e49-6a738cdcca42,2025-09-23,185018,Carlos García,carlos.garcía_185018@example.com,Brasil,BRA,Fortaleza,9339 Calle Oeste,P007,Blender,Home,2,45.00,4.40,11.60,90.00,0.00,17.10,118.70,Debit Card,Cancelled
9,50107597-f452-472f-a3a4-8789af038e1f,2026-02-14,126772,Josefa González,josefa.gonzález_126772@example.com,Brasil,BRA,São Paulo,3605 Calle Este,P013,Gaming Console,Electronics,1,500.00,3.50,10.25,500.00,0.00,95.00,605.25,Credit Card,Shipped

In [4]:
#PASO 1: ANTES DE EMPEZAR A TRABAJAR CON NUESTRA DATA (QUE SE LLAMA DF_RAW), TENEMOS QUE HACER UNA COPIA PARA PRESERVAR LA INFO ORIGINAL.
#A ESTA COPIA LA VAMOS A LLAMR DF_WORK.
#USAMOS EL MÉTODO .COPY PARA PERMITIR HACER UNA COPIA DE UN DATAFRAME Y ESTE METODO TIENE UN PARAMETRO QUE SE LLAMA "DEEP". SIGNIFICA QUE DF_WORK VA A SER UNA COPIA UNICA E INDEPENDIENTE DEL DF ORIGINAL.
#LA FUNCIÓN ES .COPY(DEEP=TRUE). FYI - POR DEFECTO LA QUERY ES "TRUE". EN CASO DE PONER "FALSE", SE HACE LA COPIA PERO SIGUEN CONECTADAS AMBAS DF.
df_work = df_raw.copy(deep = True)

In [5]:
df_work.head() #VERIFICAMOS QUE SEA LA MISMA DF QUE LA RAW.

,order_id,order_date,customer_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount,payment_method,shipping_status
0,98c01d39-0be7-4ee0-9ecf-50a50b63159a,2024-06-12,250414,Jorge Pérez,jorge.pérez_250414@example.com,Chile,CHL,Rancagua,5054 Calle Los Pinos,P012,Headphones NoiseCancelling,Electronics,1,250.00,0.30,5.45,250.00,0.00,47.50,302.95,PayPal,Delivered
1,715759ca-06c2-4b36-b86f-177b6b154a7a,2025-05-29,269884,Isabel Castro,isabel.castro_269884@example.com,Colombia,COL,Medellín,5375 Calle Los Alamos,P015,Hair Dryer,Home,1,35.00,0.60,5.90,35.00,3.50,5.99,43.38,Credit Card,Shipped
2,46e91d25-94ff-4eca-9fe7-7d7cb4683429,2025-10-04,54582,Francisco Rojas,francisco.rojas_54582@example.com,Argentina,ARG,Mar del Plata,3777 Calle Los Pinos,P008,Office Chair,Furniture,1,200.00,15.00,27.50,200.00,10.00,36.10,253.60,PayPal,Shipped
3,df2478f3-f34f-4f18-82eb-86727241b153,2024-11-19,194401,Carlos Ramírez,carlos.ramírez_194401@example.com,Perú,PER,Piura,2115 Calle Secundaria,P015,Hair Dryer,Home,1,NaN,0.60,5.90,35.00,0.00,6.65,47.55,PayPal,Delivered
4,e6a850d8-d658-46fb-9c94-4f99af54a596,2026-01-07,104597,Pedro García,pedro.garcía_104597@example.com,Argentina,ARG,Córdoba,6181 Calle Secundaria,P002,Smartphone X,Electronics,1,800.00,0.20,5.30,800.00,40.00,144.40,909.70,Bank Transfer,Delivered

In [6]:
df_work.info(show_counts = True)
#METODO INFO NOS PERMITE VER INFO GENERAL SOBRE LAS COLUMNAS DEL DF.
#CON SHOW_COUNTS = TRUE FORZAMOS EL QUERY A QUE NOS MUESTRE LOS NUMEROS DE NO-NULOS POR CADA COLUMNA

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2001000 entries, 0 to 2000999
Data columns (total 22 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   order_id            2001000 non-null  object
 1   order_date          2001000 non-null  object
 2   customer_id         2001000 non-null  int64
 3   customer_name       2001000 non-null  object
 4   customer_email      1900950 non-null  object
 5   customer_country    2001000 non-null  object
 6   country_code        2001000 non-null  object
 7   customer_city       1960988 non-null  object
 8   customer_address    2001000 non-null  object
 9   product_id          2001000 non-null  object
 10  product_name        2001000 non-null  object
 11  product_category    2001000 non-null  object
 12  quantity            2001000 non-null  int64
 13  price_per_unit      1996998 non-null  float64
 14  total_weight        1999000 non-null  float64
 15  shipping_cost       1990998 non-null  float64
 16  total_amount_gross  2001000 non-null  float64
 17  discount_amount     2001000 non-null  float64
 18  tax_amount          1980994 non-null  float64
 19  final_total_amount  2001000 non-null  float64
 20  payment_method      2001000 non-null  object
 21  shipping_status     1800888 non-null  object
dtypes: float64(7), int64(2), object(13)
memory usage: 335.9+ MB

In [7]:
df_work.columns #VER LISTA CON NOMBRE DE COLUMNAS

Index(['order_id', 'order_date', 'customer_id', 'customer_name',
       'customer_email', 'customer_country', 'country_code', 'customer_city',
       'customer_address', 'product_id', 'product_name', 'product_category',
       'quantity', 'price_per_unit', 'total_weight', 'shipping_cost',
       'total_amount_gross', 'discount_amount', 'tax_amount',
       'final_total_amount', 'payment_method', 'shipping_status'],
      dtype='object')

In [39]:
#RECUERDA QUE LOS BRACKETS [] SIRVEN PARA LLAMAR A UNA COLUMNA EN PARTICULAR DENTRO DEL DF.
#despues pones el atributo que quieres de la columna, por ejemplo .unique() nos ayuda a ver las variables unicas de la columna.

df_work['customer_country'].unique()

array(['Chile', 'Colombia', 'Argentina', 'Perú', 'Brasil', 'México',
       'Ecuador', 'Uruguay'], dtype=object)

In [40]:
#EN CASO DE QUE YO QUIERA CONTAR EL NUMERO CUALITATIVO DE VALORES EN LA COLUMNA, VA CON .NUNIQUE()
# AQUI SE VE EL VALOR DE QUE TAN GRANDE O BAJO ES LA CARDINALIDAD DE LA DATA. AL SER SOLO 8 DATOS, SE DIRIA QUE ES UNA CARDINALIDAD BAJA.
df_work['customer_country'].nunique()

8

In [41]:
df_work['customer_email'].unique()

array(['jorge.pérez_250414@example.com',
       'isabel.castro_269884@example.com',
       'francisco.rojas_54582@example.com', ...,
       'carmen.gomez_68415@example.com',
       'isabella.torres_167541@example.com',
       'juan.morales_266965@example.com'], dtype=object)

In [42]:
df_work['customer_email'].nunique()
# aqui se concluye que la cardinalidad es alta.

394329

In [44]:
df_work['payment_method'].unique()
# aqui la cardinalidad esta sesgada porque hay valores duplicados, que se tendrán que estandarizar.

array(['PayPal', 'Credit Card', 'Bank Transfer', 'Debit Card',
       'debit card', 'credit card', 'CREDIT CARD', 'PAYPAL', 'DEBIT CARD',
       'paypal', 'BANK TRANSFER', 'bank transfer'], dtype=object)

In [13]:
#CONTEMOS DE VALORES NULOS.

In [53]:
#DIFERENTES FORMAS DE HACERLO#
#1. ISNA() nos ayuda a revisar cada valor de cada columna y coloca falso/verdadero. FALSO = NO esta vacio. TRUE= SI esta vacio.
#2. .sum() nos ayuda a realizar el conteo por columna,o sea hace una pequeña lista de los valores nulos por columna.
# 3. .MEAN() para sacar el promedio. Es basicamente el %. Es decir, que % de la columna esta vacia. Le agregas al inicio 100* para sacarlo en %
# y terminamos por agregar .sort_values() para que me muestre la tabla de menor a mayor.
# si lo quieres ver de mayor a menor se usa (ascending = False)

df_work.isna().sum()
100* df_work.isna().mean().sort_values(ascending = False)

customer_city        2.00
tax_amount           1.00
shipping_cost        0.50
price_per_unit       0.20
total_weight         0.10
order_id             0.00
customer_country     0.00
customer_email       0.00
customer_name        0.00
customer_id          0.00
order_date           0.00
product_id           0.00
customer_address     0.00
country_code         0.00
quantity             0.00
product_category     0.00
product_name         0.00
total_amount_gross   0.00
discount_amount      0.00
final_total_amount   0.00
payment_method       0.00
shipping_status      0.00
dtype: float64

In [77]:
df_work['quantity'] = df_work['quantity'].abs()  #este query nos ayuda a eliminar valores negativos.
df_work.describe() #RESUMEN ESTADÍSTICO DE LAS COLUMNAS NUMÉRICAS DEL DATAFRAME

/tmp/ipykernel_40310/2625867200.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['quantity'] = df_work['quantity'].abs()  #este query nos ayuda a eliminar valores negativos.

,customer_id,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount
count,1800888.00,1800888.00,1797257.00,1799068.00,1791891.00,1800888.00,1800888.00,1782900.00,1800888.00
mean,201004.97,1.57,271.09,8.66,17.99,425.79,14.87,78.07,505.73
std,115532.18,1.21,318.72,20.06,30.10,711.25,50.28,130.73,830.39
min,1000.00,1.00,20.00,0.10,5.15,20.00,0.00,3.04,12.17
25%,100800.00,1.00,45.00,0.60,5.90,70.00,0.00,12.92,86.97
50%,200903.00,1.00,120.00,2.20,8.30,150.00,0.00,28.50,198.50
75%,301196.00,2.00,300.00,10.00,20.00,500.00,8.50,95.00,605.25
max,400999.00,10.00,1200.00,450.00,680.00,12000.00,2400.00,2280.00,14322.50

In [16]:
df_raw['product_category'].describe()
# DESCRIBE A UNA COLUMNA QUE NO SEA NUMERICA. LOS RESULTADOS QUE ARROJA, SON PEQUEÑOS DATOS.
# Hay 2001000 datos, las variables unicas son 5, donde "electronics" es el que mas se repite, exactamente 587853 veces.

count         2001000
unique              5
top       Electronics
freq           587853
Name: product_category, dtype: object

In [55]:
#VALUE.COUNTS() ES UNA TECNICA DE EXPLORACIÓN, QUE TE MUESTRA EL CONTEO DE LA FRECUENCIA CON LA QUE APARECE CADA VALOR/VARIABLE DE UNA COLUMNA QUE ESPECIFIQUES. LA COLUMNA DEBE DE SER CATEGORICA.
#este conteo ignora por default los nulos. Pero si yo le agrego el dropna = false, contara los nulos.
df_work['payment_method'].value_counts()

payment_method
Credit Card      730839
Debit Card       470918
PayPal           167209
credit card       90114
Bank Transfer     88951
CREDIT CARD       81584
debit card        58414
DEBIT CARD        52470
paypal            20959
PAYPAL            18465
bank transfer     11184
BANK TRANSFER      9781
Name: count, dtype: int64

In [60]:
#VAMOS A ESTANDARIZAR LOS NOMBRES DE LOS METODOS DE PAGO PARA QUE NO SE ESTE DUPLICANDO.
#LAS OPCIONES SON .UPPER() .LOWER() .TITLE()
# siempre es buena opción agregar .strip() para quitar espacios vacios, es como un TRIM.
df_work['payment_method'] =df_work['payment_method'].str.upper().str.strip()
df_work.head()

/tmp/ipykernel_40310/2632873021.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['payment_method'] =df_work['payment_method'].str.upper().str.strip()

,order_id,order_date,customer_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount,payment_method,shipping_status
0,98c01d39-0be7-4ee0-9ecf-50a50b63159a,2024-06-12,250414,jorge pérez,jorge.pérez_250414@example.com,Chile,CHL,Rancagua,5054 Calle Los Pinos,P012,Headphones NoiseCancelling,Electronics,1,250.00,0.30,5.45,250.00,0.00,47.50,302.95,PAYPAL,Delivered
1,715759ca-06c2-4b36-b86f-177b6b154a7a,2025-05-29,269884,isabel castro,isabel.castro_269884@example.com,Colombia,COL,Medellín,5375 Calle Los Alamos,P015,Hair Dryer,Home,1,35.00,0.60,5.90,35.00,3.50,5.99,43.38,CREDIT CARD,Shipped
2,46e91d25-94ff-4eca-9fe7-7d7cb4683429,2025-10-04,54582,francisco rojas,francisco.rojas_54582@example.com,Argentina,ARG,Mar del Plata,3777 Calle Los Pinos,P008,Office Chair,Furniture,1,200.00,15.00,27.50,200.00,10.00,36.10,253.60,PAYPAL,Shipped
3,df2478f3-f34f-4f18-82eb-86727241b153,2024-11-19,194401,carlos ramírez,carlos.ramírez_194401@example.com,Perú,PER,Piura,2115 Calle Secundaria,P015,Hair Dryer,Home,1,NaN,0.60,5.90,35.00,0.00,6.65,47.55,PAYPAL,Delivered
4,e6a850d8-d658-46fb-9c94-4f99af54a596,2026-01-07,104597,pedro garcía,pedro.garcía_104597@example.com,Argentina,ARG,Córdoba,6181 Calle Secundaria,P002,Smartphone X,Electronics,1,800.00,0.20,5.30,800.00,40.00,144.40,909.70,BANK TRANSFER,Delivered

In [63]:
# Nombramos nuevamente la tabla para ver la tabla del pull 55, pero ahora corregida.
#utilizamos el metodo de 100* y agregamos el normalize = true. Para sacar los metodos de pago utilizados en %.
df_work['payment_method'] = df_work ['payment_method'].str.upper().str.strip()
100*df_work['payment_method'].value_counts(normalize = True)

/tmp/ipykernel_40310/42450223.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_work['payment_method'] = df_work ['payment_method'].str.upper().str.strip()

payment_method
CREDIT CARD     50.12
DEBIT CARD      32.31
PAYPAL          11.47
BANK TRANSFER    6.10
Name: proportion, dtype: float64

*En esta sección vamos a ver como tratar los valores faltantes. Existen 3 tipos:*

* __MCAR (MISSING COMPLETLY AT RANDOM):__ Cada registro que es nulo lo hace sin ningún patron específico. Es decir, cualquiera de los registros tiene la misma chance de estar vacío. RECOMENDACIÓN: ELIMINAR O IMPUTAR (RELLENAR VALORES CON MEDIA O LA MEDIANA)

* __MAR (MISSING AT RANDOM):__ Hay valores nulos, pero estos se relacionan con otra columna específica. Es decir, hay valores nulos, pero estos se asocian a un unico o unicos. Por ejemplo: Quantity esta vacio pero esta relacionado con el mismo country.

* __MNAR (MISSING AT NO RANDOM):__ El valor no está o aparece nulo, pero no es al azar. Por ejemplo: Persona de áreas ricas de la ciudad, no dan su nombre por privacidad, por lo que la coluna user_name, suele tener nulos.

In [78]:
#Vamos a trabajr con la columna price per unit y quisiera saber si los valores nulos de esta se asocian con los paises.
# La primera parte de la función le pedimos que traiga los valores nulos y no nulos de la columna price per unit. Se puede ver el True/False en la query de abajo.
#Para hacer la comparación con otra columna, el .groupby() nos ayuda a comparar ambas columnas.
#Con .mean() rellenamos los valores nulos con la media.

df_work['price_per_unit'].isna().groupby(df_work['customer_country']).mean().sort_values(ascending = False)

customer_country
Ecuador     0.00
Chile       0.00
Uruguay     0.00
Argentina   0.00
Colombia    0.00
México      0.00
Brasil      0.00
Perú        0.00
Name: price_per_unit, dtype: float64

In [79]:
#IDENTIFICANDO TIPOS DE VALORES FALTANTES
df_raw['price_per_unit'].isna().groupby(df_raw['product_category']).mean().sort_values(ascending = False)

product_category
Home          0.00
Fashion       0.00
Accessories   0.00
Furniture     0.00
Electronics   0.00
Name: price_per_unit, dtype: float64

In [19]:
df_work['price_per_unit'].isna().head()

0    False
1    False
2    False
3     True
4    False
Name: price_per_unit, dtype: bool

In [20]:
df_work.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2001000 entries, 0 to 2000999
Data columns (total 22 columns):
 #   Column              Dtype
---  ------              -----
 0   order_id            object
 1   order_date          object
 2   customer_id         int64
 3   customer_name       object
 4   customer_email      object
 5   customer_country    object
 6   country_code        object
 7   customer_city       object
 8   customer_address    object
 9   product_id          object
 10  product_name        object
 11  product_category    object
 12  quantity            int64
 13  price_per_unit      float64
 14  total_weight        float64
 15  shipping_cost       float64
 16  total_amount_gross  float64
 17  discount_amount     float64
 18  tax_amount          float64
 19  final_total_amount  float64
 20  payment_method      object
 21  shipping_status     object
dtypes: float64(7), int64(2), object(13)
memory usage: 335.9+ MB

In [21]:
df_work['order_date'] = df_work['order_date'].astype('datetime64[ns]')

In [22]:
df_work = df_raw.dropna(subset = ['shipping_status'])

In [23]:
df_work.head()

,order_id,order_date,customer_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount,payment_method,shipping_status
0,98c01d39-0be7-4ee0-9ecf-50a50b63159a,2024-06-12,250414,Jorge Pérez,jorge.pérez_250414@example.com,Chile,CHL,Rancagua,5054 Calle Los Pinos,P012,Headphones NoiseCancelling,Electronics,1,250.00,0.30,5.45,250.00,0.00,47.50,302.95,PayPal,Delivered
1,715759ca-06c2-4b36-b86f-177b6b154a7a,2025-05-29,269884,Isabel Castro,isabel.castro_269884@example.com,Colombia,COL,Medellín,5375 Calle Los Alamos,P015,Hair Dryer,Home,1,35.00,0.60,5.90,35.00,3.50,5.99,43.38,Credit Card,Shipped
2,46e91d25-94ff-4eca-9fe7-7d7cb4683429,2025-10-04,54582,Francisco Rojas,francisco.rojas_54582@example.com,Argentina,ARG,Mar del Plata,3777 Calle Los Pinos,P008,Office Chair,Furniture,1,200.00,15.00,27.50,200.00,10.00,36.10,253.60,PayPal,Shipped
3,df2478f3-f34f-4f18-82eb-86727241b153,2024-11-19,194401,Carlos Ramírez,carlos.ramírez_194401@example.com,Perú,PER,Piura,2115 Calle Secundaria,P015,Hair Dryer,Home,1,NaN,0.60,5.90,35.00,0.00,6.65,47.55,PayPal,Delivered
4,e6a850d8-d658-46fb-9c94-4f99af54a596,2026-01-07,104597,Pedro García,pedro.garcía_104597@example.com,Argentina,ARG,Córdoba,6181 Calle Secundaria,P002,Smartphone X,Electronics,1,800.00,0.20,5.30,800.00,40.00,144.40,909.70,Bank Transfer,Delivered

## __Funciones en Python__

Las funciones son una metedología de generación de un esquema general de un proceso repetitivo en python. Se caracateriza al igual que cualquier función por tener entrada - proceso - salida.

In [24]:
#DEFINICIÓN FUNCIÓN BÁSICA Y f-string
def saludo_cohorte_95(cantidad_estudiantes, year):
  print(f"Hola a los {cantidad_estudiantes} estudiantes del cohorte 95 en el año {year}")

In [25]:
saludo_cohorte_95(cantidad_estudiantes = 55 , year = 2040)

Hola a los 55 estudiantes del cohorte 95 en el año 2040

In [26]:
def text_column_check(df, column_name):
  df[column_name] = df[column_name].astype('str')       #SUB-PROCESO 1: CONVERTIR AL TIPO DE DATOS ADECUADO.
  df[column_name] = df[column_name].str.strip()         #SUB-PROCESO 2: ELIMINAR ESPACIOS EN BLANCO.
  df[column_name] = df[column_name].str.lower()         #SUB-PROCESO 3: DEJAR TODO TEXTO EN MAYÚSCULAS.
  df[column_name].fillna('DESCONOCIDO', inplace = True) #SUB-PROCESO 4: IMPUTAR COLUMNA CON "DESCONOCIDO"
  df[column_name] = df[column_name].replace("nan","DESCONOCIDO") #SUB-PROCESO 5: QUITAR PALABRA nan Y SUSTUIRLA.
  return df

In [27]:
df_limpio = text_column_check(df_work,'customer_name')

/tmp/ipykernel_40310/2060691211.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].astype('str')       #SUB-PROCESO 1: CONVERTIR AL TIPO DE DATOS ADECUADO.
/tmp/ipykernel_40310/2060691211.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.strip()         #SUB-PROCESO 2: ELIMINAR ESPACIOS EN BLANCO.
/tmp/ipykernel_40310/2060691211.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.lower()         #SUB-PROCESO 3: DEJAR TODO TEXTO EN MAYÚSCULAS.
/tmp/ipykernel_40310/2060691211.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name].fillna('DESCONOCIDO', inplace = True) #SUB-PROCESO 4: IMPUTAR COLUMNA CON "DESCONOCIDO"
/tmp/ipykernel_40310/2060691211.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].replace("nan","DESCONOCIDO") #SUB-PROCESO 5: QUITAR PALABRA nan Y SUSTUIRLA.

In [28]:
df_limpio.head()

,order_id,order_date,customer_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount,payment_method,shipping_status
0,98c01d39-0be7-4ee0-9ecf-50a50b63159a,2024-06-12,250414,jorge pérez,jorge.pérez_250414@example.com,Chile,CHL,Rancagua,5054 Calle Los Pinos,P012,Headphones NoiseCancelling,Electronics,1,250.00,0.30,5.45,250.00,0.00,47.50,302.95,PayPal,Delivered
1,715759ca-06c2-4b36-b86f-177b6b154a7a,2025-05-29,269884,isabel castro,isabel.castro_269884@example.com,Colombia,COL,Medellín,5375 Calle Los Alamos,P015,Hair Dryer,Home,1,35.00,0.60,5.90,35.00,3.50,5.99,43.38,Credit Card,Shipped
2,46e91d25-94ff-4eca-9fe7-7d7cb4683429,2025-10-04,54582,francisco rojas,francisco.rojas_54582@example.com,Argentina,ARG,Mar del Plata,3777 Calle Los Pinos,P008,Office Chair,Furniture,1,200.00,15.00,27.50,200.00,10.00,36.10,253.60,PayPal,Shipped
3,df2478f3-f34f-4f18-82eb-86727241b153,2024-11-19,194401,carlos ramírez,carlos.ramírez_194401@example.com,Perú,PER,Piura,2115 Calle Secundaria,P015,Hair Dryer,Home,1,NaN,0.60,5.90,35.00,0.00,6.65,47.55,PayPal,Delivered
4,e6a850d8-d658-46fb-9c94-4f99af54a596,2026-01-07,104597,pedro garcía,pedro.garcía_104597@example.com,Argentina,ARG,Córdoba,6181 Calle Secundaria,P002,Smartphone X,Electronics,1,800.00,0.20,5.30,800.00,40.00,144.40,909.70,Bank Transfer,Delivered

In [29]:
df_limpio.isna().sum()

order_id                  0
order_date                0
customer_id               0
customer_name             0
customer_email        89918
customer_country          0
country_code              0
customer_city         36068
customer_address          0
product_id                0
product_name              0
product_category          0
quantity                  0
price_per_unit         3631
total_weight           1820
shipping_cost          8997
total_amount_gross        0
discount_amount           0
tax_amount            17988
final_total_amount        0
payment_method            0
shipping_status           0
dtype: int64

In [30]:
df_limpio_2 = text_column_check(df_work,'customer_email')

/tmp/ipykernel_40310/2060691211.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].astype('str')       #SUB-PROCESO 1: CONVERTIR AL TIPO DE DATOS ADECUADO.
/tmp/ipykernel_40310/2060691211.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.strip()         #SUB-PROCESO 2: ELIMINAR ESPACIOS EN BLANCO.
/tmp/ipykernel_40310/2060691211.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.lower()         #SUB-PROCESO 3: DEJAR TODO TEXTO EN MAYÚSCULAS.
/tmp/ipykernel_40310/2060691211.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name].fillna('DESCONOCIDO', inplace = True) #SUB-PROCESO 4: IMPUTAR COLUMNA CON "DESCONOCIDO"
/tmp/ipykernel_40310/2060691211.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].replace("nan","DESCONOCIDO") #SUB-PROCESO 5: QUITAR PALABRA nan Y SUSTUIRLA.

In [31]:
df_limpio_2.head()

,order_id,order_date,customer_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount,payment_method,shipping_status
0,98c01d39-0be7-4ee0-9ecf-50a50b63159a,2024-06-12,250414,jorge pérez,jorge.pérez_250414@example.com,Chile,CHL,Rancagua,5054 Calle Los Pinos,P012,Headphones NoiseCancelling,Electronics,1,250.00,0.30,5.45,250.00,0.00,47.50,302.95,PayPal,Delivered
1,715759ca-06c2-4b36-b86f-177b6b154a7a,2025-05-29,269884,isabel castro,isabel.castro_269884@example.com,Colombia,COL,Medellín,5375 Calle Los Alamos,P015,Hair Dryer,Home,1,35.00,0.60,5.90,35.00,3.50,5.99,43.38,Credit Card,Shipped
2,46e91d25-94ff-4eca-9fe7-7d7cb4683429,2025-10-04,54582,francisco rojas,francisco.rojas_54582@example.com,Argentina,ARG,Mar del Plata,3777 Calle Los Pinos,P008,Office Chair,Furniture,1,200.00,15.00,27.50,200.00,10.00,36.10,253.60,PayPal,Shipped
3,df2478f3-f34f-4f18-82eb-86727241b153,2024-11-19,194401,carlos ramírez,carlos.ramírez_194401@example.com,Perú,PER,Piura,2115 Calle Secundaria,P015,Hair Dryer,Home,1,NaN,0.60,5.90,35.00,0.00,6.65,47.55,PayPal,Delivered
4,e6a850d8-d658-46fb-9c94-4f99af54a596,2026-01-07,104597,pedro garcía,pedro.garcía_104597@example.com,Argentina,ARG,Córdoba,6181 Calle Secundaria,P002,Smartphone X,Electronics,1,800.00,0.20,5.30,800.00,40.00,144.40,909.70,Bank Transfer,Delivered

In [32]:
df_limpio_2.isna().sum()

order_id                  0
order_date                0
customer_id               0
customer_name             0
customer_email            0
customer_country          0
country_code              0
customer_city         36068
customer_address          0
product_id                0
product_name              0
product_category          0
quantity                  0
price_per_unit         3631
total_weight           1820
shipping_cost          8997
total_amount_gross        0
discount_amount           0
tax_amount            17988
final_total_amount        0
payment_method            0
shipping_status           0
dtype: int64

In [33]:
df_raw.isna().sum()

order_id                   0
order_date                 0
customer_id                0
customer_name              0
customer_email        100050
customer_country           0
country_code               0
customer_city          40012
customer_address           0
product_id                 0
product_name               0
product_category           0
quantity                   0
price_per_unit          4002
total_weight            2000
shipping_cost          10002
total_amount_gross         0
discount_amount            0
tax_amount             20006
final_total_amount         0
payment_method             0
shipping_status       200112
dtype: int64

In [34]:
df_work.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1800888 entries, 0 to 2000999
Data columns (total 22 columns):
 #   Column              Dtype
---  ------              -----
 0   order_id            object
 1   order_date          object
 2   customer_id         int64
 3   customer_name       object
 4   customer_email      object
 5   customer_country    object
 6   country_code        object
 7   customer_city       object
 8   customer_address    object
 9   product_id          object
 10  product_name        object
 11  product_category    object
 12  quantity            int64
 13  price_per_unit      float64
 14  total_weight        float64
 15  shipping_cost       float64
 16  total_amount_gross  float64
 17  discount_amount     float64
 18  tax_amount          float64
 19  final_total_amount  float64
 20  payment_method      object
 21  shipping_status     object
dtypes: float64(7), int64(2), object(13)
memory usage: 316.0+ MB

In [35]:
df_limpiar_1 = text_column_check(df_work,'customer_name')
df_limpiar_2 = text_column_check(df_work, 'c')

/tmp/ipykernel_40310/2060691211.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].astype('str')       #SUB-PROCESO 1: CONVERTIR AL TIPO DE DATOS ADECUADO.
/tmp/ipykernel_40310/2060691211.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.strip()         #SUB-PROCESO 2: ELIMINAR ESPACIOS EN BLANCO.
/tmp/ipykernel_40310/2060691211.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.lower()         #SUB-PROCESO 3: DEJAR TODO TEXTO EN MAYÚSCULAS.
/tmp/ipykernel_40310/2060691211.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name].fillna('DESCONOCIDO', inplace = True) #SUB-PROCESO 4: IMPUTAR COLUMNA CON "DESCONOCIDO"
/tmp/ipykernel_40310/2060691211.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].replace("nan","DESCONOCIDO") #SUB-PROCESO 5: QUITAR PALABRA nan Y SUSTUIRLA.

KeyError: 'c'

## __BUCLES LÓGICOS EN PYTHON__

Estructuras que nos permiten repetir proceso bajo ciertas características.

### __CLICO FOR__

In [64]:
mi_lista = [100,200,300,400,500,600,700,800,900,1000]

for a in mi_lista:
  print(f"- El elememento que estoy imprimiendo es el: {5*a}")

- El elememento que estoy imprimiendo es el: 500
- El elememento que estoy imprimiendo es el: 1000
- El elememento que estoy imprimiendo es el: 1500
- El elememento que estoy imprimiendo es el: 2000
- El elememento que estoy imprimiendo es el: 2500
- El elememento que estoy imprimiendo es el: 3000
- El elememento que estoy imprimiendo es el: 3500
- El elememento que estoy imprimiendo es el: 4000
- El elememento que estoy imprimiendo es el: 4500
- El elememento que estoy imprimiendo es el: 5000

In [65]:
for i in range(10): #[0,1,2,3,4,5,6,7,8,9]
  mi_lista[i] = 4*mi_lista[i]

In [66]:
print(mi_lista)

[400, 800, 1200, 1600, 2000, 2400, 2800, 3200, 3600, 4000]

In [67]:
df_work.columns

Index(['order_id', 'order_date', 'customer_id', 'customer_name',
       'customer_email', 'customer_country', 'country_code', 'customer_city',
       'customer_address', 'product_id', 'product_name', 'product_category',
       'quantity', 'price_per_unit', 'total_weight', 'shipping_cost',
       'total_amount_gross', 'discount_amount', 'tax_amount',
       'final_total_amount', 'payment_method', 'shipping_status'],
      dtype='object')

In [68]:
lista_campos = ['customer_city','customer_email','shipping_status']

for campo in lista_campos:
  df_transformado = text_column_check(df_raw,campo)

In [69]:
df_transformado.head()

,order_id,order_date,customer_id,customer_name,customer_email,customer_country,country_code,customer_city,customer_address,product_id,product_name,product_category,quantity,price_per_unit,total_weight,shipping_cost,total_amount_gross,discount_amount,tax_amount,final_total_amount,payment_method,shipping_status
0,98c01d39-0be7-4ee0-9ecf-50a50b63159a,2024-06-12,250414,Jorge Pérez,jorge.pérez_250414@example.com,Chile,CHL,rancagua,5054 Calle Los Pinos,P012,Headphones NoiseCancelling,Electronics,1,250.00,0.30,5.45,250.00,0.00,47.50,302.95,PayPal,delivered
1,715759ca-06c2-4b36-b86f-177b6b154a7a,2025-05-29,269884,Isabel Castro,isabel.castro_269884@example.com,Colombia,COL,medellín,5375 Calle Los Alamos,P015,Hair Dryer,Home,1,35.00,0.60,5.90,35.00,3.50,5.99,43.38,Credit Card,shipped
2,46e91d25-94ff-4eca-9fe7-7d7cb4683429,2025-10-04,54582,Francisco Rojas,francisco.rojas_54582@example.com,Argentina,ARG,mar del plata,3777 Calle Los Pinos,P008,Office Chair,Furniture,1,200.00,15.00,27.50,200.00,10.00,36.10,253.60,PayPal,shipped
3,df2478f3-f34f-4f18-82eb-86727241b153,2024-11-19,194401,Carlos Ramírez,carlos.ramírez_194401@example.com,Perú,PER,piura,2115 Calle Secundaria,P015,Hair Dryer,Home,1,NaN,0.60,5.90,35.00,0.00,6.65,47.55,PayPal,delivered
4,e6a850d8-d658-46fb-9c94-4f99af54a596,2026-01-07,104597,Pedro García,pedro.garcía_104597@example.com,Argentina,ARG,córdoba,6181 Calle Secundaria,P002,Smartphone X,Electronics,1,800.00,0.20,5.30,800.00,40.00,144.40,909.70,Bank Transfer,delivered

In [70]:
df_transformado.isna().sum()

order_id                  0
order_date                0
customer_id               0
customer_name             0
customer_email            0
customer_country          0
country_code              0
customer_city             0
customer_address          0
product_id                0
product_name              0
product_category          0
quantity                  0
price_per_unit         4002
total_weight           2000
shipping_cost         10002
total_amount_gross        0
discount_amount           0
tax_amount            20006
final_total_amount        0
payment_method            0
shipping_status           0
dtype: int64

### __WHILE__

Ejecuta un proceso, mientras se cupla una condición específica.

In [ ]:
valor = 0

In [ ]:
while valor < 100:
  print(valor)
  valor = valor + 1

In [ ]:
mis_columnas = df_raw.columns
mis_columnas[-2]

In [ ]:
while len(df_raw.columns) > :
    columna_a_borrar = df_raw.columns[-1]
    df_raw.drop(columns=[columna_a_borrar], inplace=True)
    print(f"- Eliminada: {columna_a_borrar}")

In [ ]:
df_raw.head()

In [ ]:
len(df_raw)

In [ ]:
df_work.isna().sum()

In [ ]:
def numeric_column_check(df,column_name):
  df[column_name] = pd.to_numeric(df[column_name], errors='coerce') #SUB-PROCESO 1: DEFINIR COMO NUMÉRICO.
  median_column   = df[column_name].median()
  df[column_name].fillna(median_column, inplace = True)
  return df

In [ ]:
df_column_imputation_1 = numeric_column_check(df = df_work,column_name = 'price_per_unit')

In [ ]:
df_column_imputation_1.isna().sum()

In [ ]:
lista_numeric = ["total_weight","shipping_cost","tax_amount"]

In [ ]:
for elemento in lista_numeric:
  df_resultado = numeric_column_check(df = df_work,column_name = elemento)

In [ ]:
df_resultado.isna().sum()